"""baseline_current_schema

Revision ID: 0e36d70f68ce
Revises: 
Create Date: 2026-09-06 15:59:02.433328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e36d70f68ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=10), nullable=True),
    sa.Column('is_backfilled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timeframe', 'timestamp', name='uix_candle_key')
    )
    op.create_index('ix_candle_ticker_tf_ts', 'candles', ['ticker', 'timeframe', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_index(op.f('ix_candles_ticker'), 'candles', ['ticker'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('current_day_candle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trading_date', name='uix_ticker_trading_date')
    )
    op.create_index(op.f('ix_current_day_candle_ticker'), 'current_day_candle', ['ticker'], unique=False)
    op.create_index(op.f('ix_current_day_candle_trading_date'), 'current_day_candle', ['trading_date'], unique=False)
    op.create_index('ix_currentdaycandle_ticker_date', 'current_day_candle', ['ticker', sa.literal_column('trading_date DESC')], unique=False)
    op.create_table('deprecated_intraday_candles_15min',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timestamp', name='uix_ticker_timestamp_15min')
    )
    op.create_index('idx_15min_ticker_ts', 'deprecated_intraday_candles_15min', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_15min_id'), 'deprecated_intraday_candles_15min', ['id'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_15min_ticker'), 'deprecated_intraday_candles_15min', ['ticker'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_15min_timestamp'), 'deprecated_intraday_candles_15min', ['timestamp'], unique=False)
    op.create_table('deprecated_intraday_candles_1h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timestamp', name='uix_ticker_timestamp_1h')
    )
    op.create_index('idx_1h_ticker_ts', 'deprecated_intraday_candles_1h', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_1h_id'), 'deprecated_intraday_candles_1h', ['id'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_1h_ticker'), 'deprecated_intraday_candles_1h', ['ticker'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_1h_timestamp'), 'deprecated_intraday_candles_1h', ['timestamp'], unique=False)
    op.create_table('deprecated_intraday_candles_1min',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timestamp', name='uix_ticker_timestamp_1min')
    )
    op.create_index('idx_1min_ticker_ts', 'deprecated_intraday_candles_1min', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_1min_id'), 'deprecated_intraday_candles_1min', ['id'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_1min_ticker'), 'deprecated_intraday_candles_1min', ['ticker'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_1min_timestamp'), 'deprecated_intraday_candles_1min', ['timestamp'], unique=False)
    op.create_table('deprecated_intraday_candles_30min',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timestamp', name='uix_ticker_timestamp_30min')
    )
    op.create_index('idx_30min_ticker_ts', 'deprecated_intraday_candles_30min', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_30min_id'), 'deprecated_intraday_candles_30min', ['id'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_30min_ticker'), 'deprecated_intraday_candles_30min', ['ticker'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_30min_timestamp'), 'deprecated_intraday_candles_30min', ['timestamp'], unique=False)
    op.create_table('deprecated_intraday_candles_5min',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timestamp', name='uix_ticker_timestamp_5min')
    )
    op.create_index('idx_5min_ticker_ts', 'deprecated_intraday_candles_5min', ['ticker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_5min_id'), 'deprecated_intraday_candles_5min', ['id'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_5min_ticker'), 'deprecated_intraday_candles_5min', ['ticker'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_candles_5min_timestamp'), 'deprecated_intraday_candles_5min', ['timestamp'], unique=False)
    op.create_table('deprecated_intraday_ticks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deprecated_intraday_ticks_id'), 'deprecated_intraday_ticks', ['id'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_ticks_ticker'), 'deprecated_intraday_ticks', ['ticker'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_ticks_timestamp'), 'deprecated_intraday_ticks', ['timestamp'], unique=False)
    op.create_index(op.f('ix_deprecated_intraday_ticks_trading_date'), 'deprecated_intraday_ticks', ['trading_date'], unique=False)
    op.create_table('fii_dii_flows',
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('fii_cash_cr', sa.Float(), nullable=True),
    sa.Column('dii_cash_cr', sa.Float(), nullable=True),
    sa.Column('fii_fo_cr', sa.Float(), nullable=True),
    sa.Column('net_total_cr', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_fii_dii_flows_date'), 'fii_dii_flows', ['date'], unique=False)
    op.create_table('holidays',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_table('intraday_prefill_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tickers_total', sa.Integer(), nullable=True),
    sa.Column('tickers_skipped', sa.Integer(), nullable=True),
    sa.Column('tickers_fetched', sa.Integer(), nullable=True),
    sa.Column('tickers_no_data', sa.Integer(), nullable=True),
    sa.Column('tickers_partial', sa.Integer(), nullable=True),
    sa.Column('tickers_failed', sa.Integer(), nullable=True),
    sa.Column('candles_inserted', sa.Integer(), nullable=True),
    sa.Column('candles_existed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_detail', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date')
    )
    op.create_index(op.f('ix_intraday_prefill_jobs_id'), 'intraday_prefill_jobs', ['id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_table('market_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date', 'session_type', name='uix_session')
    )
    op.create_index(op.f('ix_market_sessions_id'), 'market_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_market_sessions_session_date'), 'market_sessions', ['session_date'], unique=False)
    op.create_table('migration_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_fetched', sa.BigInteger(), nullable=True),
    sa.Column('rows_inserted', sa.BigInteger(), nullable=True),
    sa.Column('checksum_src', sa.String(length=64), nullable=True),
    sa.Column('checksum_db', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'tier', name='uix_migration_job')
    )
    op.create_index('idx_migration_jobs_tier_status', 'migration_jobs', ['tier', 'status'], unique=False)
    op.create_index(op.f('ix_migration_jobs_id'), 'migration_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_migration_jobs_ticker'), 'migration_jobs', ['ticker'], unique=False)
    op.create_table('retention_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('last_ticker', sa.String(length=50), nullable=True),
    sa.Column('rows_source', sa.BigInteger(), nullable=True),
    sa.Column('rows_target', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_jobs_id'), 'retention_jobs', ['id'], unique=False)
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uix_ticker_date')
    )
    op.create_index(op.f('ix_stock_data_date'), 'stock_data', ['date'], unique=False)
    op.create_index(op.f('ix_stock_data_id'), 'stock_data', ['id'], unique=False)
    op.create_index(op.f('ix_stock_data_ticker'), 'stock_data', ['ticker'], unique=False)
    op.create_index('ix_stock_data_ticker_date_desc', 'stock_data', ['ticker', sa.literal_column('date DESC')], unique=False)
    op.create_table('stock_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', name='uix_ticker_exchange')
    )
    op.create_index('ix_metadata_is_premium', 'stock_metadata', ['is_premium'], unique=False, postgresql_where=sa.text('is_premium = true'))
    op.create_index(op.f('ix_stock_metadata_id'), 'stock_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_stock_metadata_ticker'), 'stock_metadata', ['ticker'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token_jti'), 'token_blacklist', ['token_jti'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('virtual_balance', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('stock_name', sa.String(length=255), nullable=True),
    sa.Column('position_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('closing_price', sa.Float(), nullable=True),
    sa.Column('total_investment', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('close_type', sa.String(length=20), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('tp_edit_count', sa.Integer(), nullable=True),
    sa.Column('sl_edit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_user_status', 'positions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_positions_created_at'), 'positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_ticker'), 'positions', ['ticker'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('user_chart_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('drawings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uix_user_chart_settings')
    )
    op.create_index(op.f('ix_user_chart_settings_id'), 'user_chart_settings', ['id'], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uix_user_watchlist_ticker')
    )
    op.create_index(op.f('ix_user_watchlist_id'), 'user_watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_user_watchlist_user_id'), 'user_watchlist', ['user_id'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('stock_name', sa.String(length=255), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('position_type', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('execution_price', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('locked_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_position_id'), 'orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('stock_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('position_type', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_position_id'), 'transactions', ['position_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_position_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_ticker'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_position_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_orders_user_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_user_watchlist_user_id'), table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_id'), table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index(op.f('ix_user_chart_settings_id'), table_name='user_chart_settings')
    op.drop_table('user_chart_settings')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_ticker'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_created_at'), table_name='positions')
    op.drop_index('idx_positions_user_status', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_token_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_stock_metadata_ticker'), table_name='stock_metadata')
    op.drop_index(op.f('ix_stock_metadata_id'), table_name='stock_metadata')
    op.drop_index('ix_metadata_is_premium', table_name='stock_metadata', postgresql_where=sa.text('is_premium = true'))
    op.drop_table('stock_metadata')
    op.drop_index('ix_stock_data_ticker_date_desc', table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_ticker'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_id'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_date'), table_name='stock_data')
    op.drop_table('stock_data')
    op.drop_index(op.f('ix_retention_jobs_id'), table_name='retention_jobs')
    op.drop_table('retention_jobs')
    op.drop_index(op.f('ix_migration_jobs_ticker'), table_name='migration_jobs')
    op.drop_index(op.f('ix_migration_jobs_id'), table_name='migration_jobs')
    op.drop_index('idx_migration_jobs_tier_status', table_name='migration_jobs')
    op.drop_table('migration_jobs')
    op.drop_index(op.f('ix_market_sessions_session_date'), table_name='market_sessions')
    op.drop_index(op.f('ix_market_sessions_id'), table_name='market_sessions')
    op.drop_table('market_sessions')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_intraday_prefill_jobs_id'), table_name='intraday_prefill_jobs')
    op.drop_table('intraday_prefill_jobs')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_fii_dii_flows_date'), table_name='fii_dii_flows')
    op.drop_table('fii_dii_flows')
    op.drop_index(op.f('ix_deprecated_intraday_ticks_trading_date'), table_name='deprecated_intraday_ticks')
    op.drop_index(op.f('ix_deprecated_intraday_ticks_timestamp'), table_name='deprecated_intraday_ticks')
    op.drop_index(op.f('ix_deprecated_intraday_ticks_ticker'), table_name='deprecated_intraday_ticks')
    op.drop_index(op.f('ix_deprecated_intraday_ticks_id'), table_name='deprecated_intraday_ticks')
    op.drop_table('deprecated_intraday_ticks')
    op.drop_index(op.f('ix_deprecated_intraday_candles_5min_timestamp'), table_name='deprecated_intraday_candles_5min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_5min_ticker'), table_name='deprecated_intraday_candles_5min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_5min_id'), table_name='deprecated_intraday_candles_5min')
    op.drop_index('idx_5min_ticker_ts', table_name='deprecated_intraday_candles_5min')
    op.drop_table('deprecated_intraday_candles_5min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_30min_timestamp'), table_name='deprecated_intraday_candles_30min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_30min_ticker'), table_name='deprecated_intraday_candles_30min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_30min_id'), table_name='deprecated_intraday_candles_30min')
    op.drop_index('idx_30min_ticker_ts', table_name='deprecated_intraday_candles_30min')
    op.drop_table('deprecated_intraday_candles_30min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_1min_timestamp'), table_name='deprecated_intraday_candles_1min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_1min_ticker'), table_name='deprecated_intraday_candles_1min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_1min_id'), table_name='deprecated_intraday_candles_1min')
    op.drop_index('idx_1min_ticker_ts', table_name='deprecated_intraday_candles_1min')
    op.drop_table('deprecated_intraday_candles_1min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_1h_timestamp'), table_name='deprecated_intraday_candles_1h')
    op.drop_index(op.f('ix_deprecated_intraday_candles_1h_ticker'), table_name='deprecated_intraday_candles_1h')
    op.drop_index(op.f('ix_deprecated_intraday_candles_1h_id'), table_name='deprecated_intraday_candles_1h')
    op.drop_index('idx_1h_ticker_ts', table_name='deprecated_intraday_candles_1h')
    op.drop_table('deprecated_intraday_candles_1h')
    op.drop_index(op.f('ix_deprecated_intraday_candles_15min_timestamp'), table_name='deprecated_intraday_candles_15min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_15min_ticker'), table_name='deprecated_intraday_candles_15min')
    op.drop_index(op.f('ix_deprecated_intraday_candles_15min_id'), table_name='deprecated_intraday_candles_15min')
    op.drop_index('idx_15min_ticker_ts', table_name='deprecated_intraday_candles_15min')
    op.drop_table('deprecated_intraday_candles_15min')
    op.drop_index('ix_currentdaycandle_ticker_date', table_name='current_day_candle')
    op.drop_index(op.f('ix_current_day_candle_trading_date'), table_name='current_day_candle')
    op.drop_index(op.f('ix_current_day_candle_ticker'), table_name='current_day_candle')
    op.drop_table('current_day_candle')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_ticker'), table_name='candles')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_index('ix_candle_ticker_tf_ts', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
