-- v005: Add is_premium flag to stock_metadata for distinguishing
-- the 213 premium tickers (full intraday retention) from standard ones.

ALTER TABLE stock_metadata ADD COLUMN IF NOT EXISTS is_premium BOOLEAN NOT NULL DEFAULT FALSE;

-- Mark the 213 premium tickers
UPDATE stock_metadata SET is_premium = TRUE WHERE ticker IN (
'AAATECH','AARON','ABFRL','ABLBL','ADANIENT','ADANIPORTS','AEROFLEX','AKSHAR',
'ALOKINDS','AMBUJACEM','ARSSBL','ARTEMISMED','ASIANPAINT','ATALREAL','AVL',
'AXISBANK','AXISGOLD','AXITA','BAJAJHFL','BAJFINANCE','BANKNIFTY','BELRISE',
'BHARTIARTL','BHARTIHEXA','BIOCON','CANFINHOME','CANHLIFE','CASTROLIND',
'CENTURYPLY','CERA','COALINDIA','COLPAL','DCXINDIA','DGCONTENT','DIGIDRIVE',
'DOMS','DPEL','DREDGECORP','DRREDDY','DWARKESH','ELECTCAST','EMBDL','ESCORTS',
'ETERNAL','EXIDEIND','FABTECH','FEDERALBNK','FMCGIETF','GABRIEL','GAIL',
'GATECH','GENCON','GILLETTE','GKENERGY','GMDCLTD','GMRAIRPORT','GODREJAGRO',
'GOLDCASE','GRASIM','GREENPOWER','GRINDWELL','HBLENGINE','HCLTECH','HDFCBANK',
'HDFCGOLD','HDFCLIQUID','HDFCMID150','HDFCPVTBAN','HINDALCO','HINDUNILVR',
'HINDZINC','HOMEFIRST','HPAL','ICICIBANK','ICRA','IEX','INDUSTOWER','INFY',
'INOXWIND','INTENTECH','IOC','IRCON','IRCTC','IREDA','IRFC','ITC','JAINREC',
'JARO','JAYNECOIND','JINDWORLD','JISLJALEQS','JSWCEMENT','JSWSTEEL',
'JUBLFOOD','JYOTISTRUC','KALAMANDIR','KOTAKBANK','KSHINTL','LANCORHOL',
'LEMERITE','LICI','LINC','LIQUIDCASE','LLOYDSENGG','LT','LTF','LYKALABS',
'M&MFIN','MAANALU','MANAKCOAT','MARKOLINES','MARUTI','METALIETF','MIDCAP',
'MOIL','MRPL','MSUMI','MULTICAP','NATIONALUM','NAZARA','NDRAUTO','NEWGEN',
'NHPC','NIFTY','NMDC','NOCIL','NORTHARC','NSLNISP','NTPC','NTPCGREEN','OIL',
'OILIETF','ONGC','ORIENTCEM','PAISALO','PAR','PARADEEP','PCJEWELLER',
'PINELABS','PIRAMALFIN','POCL','POWERGRID','PTCIL','PVTBANKADD','PWL',
'QUINT','RAILTEL','RAYMOND','RBLBANK','RCF','RELIANCE','RELTD','RENUKA',
'ROLEXRINGS','SAATVIKGL','SADBHAV','SAGILITY','SAIL','SAMMAANCAP','SANDUMA',
'SBC','SBIN','SBISILVER','SCHAND','SENSEX','SETFGOLD','SHAILY','SHAKTIPUMP',
'SHRIRAMFIN','SHYAMCENT','SILVERBEES','SJVN','SMALLCAP','SOUTHBANK',
'SPECIALITY','STALLION','STEELXIND','SUNPHARMA','SURYAROSNI','SURYODAY',
'SUTLEJTEX','TARIL','TATAELXSI','TATASTEEL','TCIEXP','TCS','TEXRAIL',
'TIMETECHNO','TIMKEN','TIPSFILMS','TITAGARH','TITAN','TMCV','TMPV','TPHQ',
'TRIDENT','UFO','UJJIVANSFB','ULTRACEMCO','ULTRAMAR','UNIONBANK','UNITDSPR',
'UNITECH','URBANCO','VEDL','VIDYAWIRES','VINCOFE','VSTTILLERS','WALCHANNAG',
'WIPRO','YESBANK','ZEEL','ZEEMEDIA'
);

-- Create index for fast queries
CREATE INDEX IF NOT EXISTS idx_stock_metadata_is_premium ON stock_metadata(is_premium);
